version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"  # Make sure this matches your settings.py
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  backend:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - ./backend/core/utils:/app/core/utils
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
      - DJANGO_SETTINGS_MODULE=core.settings.local
      - DEBUG=True
      - CORS_ORIGIN_ALLOW_ALL=True
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - POSTGRES_DB=dbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=neuhu-db1234
      - POSTGRES_HOST=neuhu-db-1.cl2iee4myu5i.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CHANNEL_LAYERS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  
  
  celery:
    build: ./backend
    command: celery -A core worker -l INFO
    volumes:
      - ./backend:/app
    environment:
      - C_FORCE_ROOT=true
      - DJANGO_ENV=development
      - DJANGO_SETTINGS_MODULE=core.settings.local
      - DEBUG=True
      - CORS_ORIGIN_ALLOW_ALL=True
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - POSTGRES_DB=dbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=neuhu-db1234
      - POSTGRES_HOST=neuhu-db-1.cl2iee4myu5i.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CHANNEL_LAYERS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

  celery-beat:
    build: ./backend
    command: celery -A core beat -l INFO
    volumes:
      - ./backend:/app
    environment:
      - C_FORCE_ROOT=true
      - DJANGO_ENV=development
      - DJANGO_SETTINGS_MODULE=core.settings.local
      - DEBUG=True
      - CORS_ORIGIN_ALLOW_ALL=True
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - POSTGRES_DB=dbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=neuhu-db1234
      - POSTGRES_HOST=neuhu-db-1.cl2iee4myu5i.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CHANNEL_LAYERS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge